### ISSUE TITLE
The image is not displayed in foreground.

### ISSUE THREAD

**Issue by exabugs** [rithik-dev/firebase_notifications_handler#3]
[English]
Thank you for the very useful library.

The procedure for notifying images on iOS is as follows.
https://firebase.google.com/docs/cloud-messaging/ios/send-image

When I receive a message in the foreground, the image is not displayed.

---

[Japanese]
とても便利なライブラリをありがとうございます。

iOS で画像を通知する手順は以下
https://firebase.google.com/docs/cloud-messaging/ios/send-image?hl=ja

フォアグラウンドでメッセージを受けた時、画像が表示されないです。

![S__4595715](https://user-images.githubusercontent.com/1234874/220846149-a9234cee-b5f7-4e39-b8fa-7c434d000b60.png)

**Comment by rithik-dev** [comment]
Hey @exabugs, I'm currently working on a refactor of this library, and will fix this in the latest version.

**Comment by rithik-dev** [comment]
Hey @exabugs, the fix for this is live on the `major-refactor` branch. I'm currently working on some more things before the new release. Have to update the README because of a lot of breaking changes...

However, you can use it already using:
```
  firebase_notifications_handler:
    git:
      url: https://github.com/rithik-dev/firebase_notifications_handler.git
      ref: df127ad117831d8b70a0de29764ee4f8010ffde5
```

The README is still to be updated, let me know if you face any issues migrating from the older version...
